# Generated by Django 2.2.3 on 2019-08-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moringa_value', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('moringa_value',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('moringa_values', models.ManyToManyField(to='values.Value')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
