# Generated by Django 2.2.3 on 2019-08-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='moringa_values',
            field=models.ManyToManyField(related_name='val', related_query_name='qval', to='values.Value'),
        ),
    ]
