# Generated by Django 2.2.3 on 2019-08-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0002_auto_20190818_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='moringa_values',
            field=models.ManyToManyField(blank=True, related_name='val', related_query_name='qval', to='values.Value'),
        ),
    ]
